export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ padding: "0px", boxSizing: "border-box", margin: "0" }}>
        {children}
      </body>
    </html>
  );
}
